//
//  BladeLengthStyleKit.h
//  ProjectName
//
//  Created by Max von Hippel on 8/27/16.
//  Copyright (c) 2016 Linked & Loaded. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BladeLengthStyleKit : NSObject

// Drawing Methods
+ (void)drawCanvas1WithBlade_length: (CGFloat)blade_length;

@end
