//
//  KnifeStyleKit.h
//  ProjectName
//
//  Created by Max von Hippel on 8/24/16.
//  Copyright (c) 2016 Linked & Loaded. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface KnifeStyleKit : NSObject

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas2;
+ (void)drawCanvas3;
+ (void)drawCanvas4;
+ (void)drawCanvas5;
+ (void)drawCanvas6;
+ (void)drawCanvas7;
+ (void)drawCanvas8;
+ (void)drawCanvas9;
+ (void)drawCanvas10;
+ (void)drawCanvas11;
+ (void)drawCanvas12;
+ (void)drawCanvas13;
+ (void)drawCanvas14;
+ (void)drawCanvas15;
+ (void)drawCanvas16;
+ (void)drawCanvas17;
+ (void)drawCanvas18;
+ (void)drawCanvas19;
+ (void)drawCanvas20;
+ (void)drawCanvas21;
+ (void)drawCanvas22;
+ (void)drawCanvas23;
+ (void)drawCanvas24;
+ (void)drawCanvas25;
+ (void)drawCanvas26;

@end
