//
//  MaterialStyleKit.h
//  ProjectName
//
//  Created by Max von Hippel on 8/26/16.
//  Copyright (c) 2016 Linked & Loaded. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MaterialStyleKit : NSObject

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas2;
+ (void)drawCanvas3;
+ (void)drawCanvas4;
+ (void)drawCanvas5;
+ (void)drawCanvas6;

@end
