//
//  OwnWantStyleKit.h
//  ProjectName
//
//  Created by Max von Hippel on 8/25/16.
//  Copyright (c) 2016 Linked & Loaded. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface OwnWantStyleKit : NSObject

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas2;

@end
