# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’
workspace 'pod box'

target 'pod box' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for pod box
  pod 'BNRSSFeedParser', '~> 2.1'

  target 'pod boxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pod boxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
