//
//  EthansStyleKit.h
//  Card Creators
//
//  Created by Max von Hippel on 7/17/16.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface EthansStyleKit : NSObject

// Drawing Methods
+ (void)drawCanvas1;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
